name: "Revision CI Workflow"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - closed
  workflow_dispatch:

jobs:
  on-push-event:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: print greeting
        run: |
          echo "Hello from Github runner"
      - name: check runner environment
        run: |
          env
          ls /
          ls /home
